package com.parentguard.parent.ui.screens; import androidx.compose.foundation.background; import androidx.compose.foundation.layout.*; import androidx.compose.foundation.shape.RoundedCornerShape; import androidx.compose.material3.*; import androidx.compose.runtime.*; import androidx.compose.ui.Alignment; import androidx.compose.ui.Modifier; import androidx.compose.ui.graphics.Color; import androidx.compose.ui.text.font.FontWeight; import androidx.compose.ui.text.input.PasswordVisualTransformation; import androidx.compose.ui.unit.dp; import androidx.compose.ui.unit.sp; import androidx.lifecycle.viewmodel.compose.viewModel; import androidx.navigation.NavHostController; import com.parentguard.parent.ui.Routes; import com.parentguard.parent.viewmodel.ParentViewModel

@Composable fun LoginScreen(navController: NavHostController){val vm:ParentViewModel=viewModel();var u by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};var isReg by remember{mutableStateOf(false)};val loading by vm.loading.collectAsState();val error by vm.error.collectAsState();val token by vm.token.collectAsState()
LaunchedEffect(token){if(!token.isNullOrEmpty())navController.navigate(Routes.Home){popUpTo(Routes.Login){inclusive=true}}}
Column(Modifier.fillMaxSize().background(Color(0xFFF5F5F5)).padding(32.dp),horizontalAlignment=Alignment.CenterHorizontally){
Spacer(Modifier.height(80.dp));Text("📱",fontSize=64.sp);Text("家长助手",fontSize=28.sp,fontWeight=FontWeight.Bold);Text(if(isReg)"注册账号" else "登录账号",fontSize=14.sp,color=Color.Gray);Spacer(Modifier.height(32.dp))
OutlinedTextField(u,{u=it},label={Text("用户名")},modifier=Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp),singleLine=true);Spacer(Modifier.height(12.dp))
OutlinedTextField(p,{p=it},label={Text("密码")},modifier=Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp),singleLine=true,visualTransformation=PasswordVisualTransformation())
if(error!=null)Text(error!!,color=Color(0xFFFF3B30),fontSize=13.sp,modifier=Modifier.padding(top=8.dp))
Spacer(Modifier.height(24.dp));Button(onClick={vm.clearError();if(isReg)vm.register(u,p) else vm.login(u,p)},modifier=Modifier.fillMaxWidth().height(50.dp),shape=RoundedCornerShape(12.dp),colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF1A73E8)),enabled=u.isNotBlank()&&p.length>=6&&!loading){if(loading)CircularProgressIndicator(Modifier.size(20.dp),color=Color.White,strokeWidth=2.dp) else Text(if(isReg)"注册" else "登录",fontSize=16.sp)}
Spacer(Modifier.height(12.dp));TextButton(onClick={isReg=!isReg;vm.clearError()}){Text(if(isReg)"已有账号？去登录" else "没有账号？去注册",color=Color(0xFF1A73E8))}}
